import { Router, type IRouter } from "express";

import apiKeysRouter from "./api-keys";
import installationRouter from "./installation";
import formsRouter from "./forms";
import knowledgeRouter from "./knowledge";
import assistantRouter from "./assistant";
import appointmentsRouter from "./appointments";
import automationsRouter from "./automations";
import playbooksRouter from "./playbooks";
import reactivationRouter from "./reactivation";
import captureRouter from "./capture";
import contactsRouter from "./contacts";
import dashboardRouter from "./dashboard";
import leadsRouter from "./leads";
import meRouter from "./me";
import publicRouter from "./public";
import unsubscribeRouter from "./unsubscribe";
import settingsRouter from "./settings";
import tagsRouter from "./tags";
import tasksRouter from "./tasks";
import templatesRouter from "./templates";
import webhooksRouter from "./webhooks";
import estimatesRouter from "./estimates";
import projectsRouter from "./projects";
import storageRouter from "./storage";
import portalRouter from "./portal";
import googleReviewsRouter from "./google-reviews";
import orgsRouter from "./orgs";
import onboardingRouter from "./onboarding";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(meRouter);
router.use(contactsRouter);
router.use(leadsRouter);
router.use(estimatesRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(appointmentsRouter);
router.use(dashboardRouter);
router.use(reportsRouter);
router.use(assistantRouter);
router.use(settingsRouter);
router.use(apiKeysRouter);
router.use(installationRouter);
router.use(knowledgeRouter);
router.use(formsRouter);
router.use(templatesRouter);
router.use(automationsRouter);
router.use(playbooksRouter);
router.use(reactivationRouter);
router.use(captureRouter);
router.use(webhooksRouter);
router.use(tagsRouter);
router.use(publicRouter);
router.use(unsubscribeRouter);
router.use(storageRouter);
router.use(portalRouter);
router.use(googleReviewsRouter);
router.use(orgsRouter);
router.use(onboardingRouter);

export default router;
