import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { Resvg } from "@resvg/resvg-js";

/**
 * Server-rendered Open Graph share cards for service areas that exist only in
 * org site config (the website's static areas ship committed PNGs generated by
 * artifacts/website/scripts/generate-og-images.mjs; this mirrors that card's
 * layout so config-added areas get a matching link preview instead of the
 * generic og-default.png).
 */

/**
 * Brand tokens shared (by contract) with the website's build-time card script.
 * The og-card-brand-parity test parses generate-og-images.mjs and fails when
 * these drift from the values that script uses, so a design tweak in one
 * renderer can't silently leave the other off-brand. Update both together.
 */
export const OG_CARD_BRAND = {
  width: 1200,
  height: 630,
  navy: "#0b1424",
  accent: "#38bdf8",
  sublineColor: "#cbd5e1",
  headlineSize: 72,
  sublineSize: 30,
  brandLineSize: 26,
  footerBarHeight: 14,
  leftMargin: 72,
  fontFamily: "DejaVu Sans",
  brandSeparator: "   •   ",
  brandSuffix: "Open 24/7",
} as const;

const WIDTH = OG_CARD_BRAND.width;
const HEIGHT = OG_CARD_BRAND.height;
const NAVY = OG_CARD_BRAND.navy;
const ACCENT = OG_CARD_BRAND.accent;

const moduleDir = path.dirname(fileURLToPath(import.meta.url));

/**
 * The DejaVu fonts are vendored under the artifact's assets/ dir so rendering
 * doesn't depend on system fontconfig. The module may run from src/ (vitest)
 * or dist/ (bundle), so probe both relative locations plus the cwd.
 */
function findFont(file: string): string {
  const candidates = [
    path.resolve(moduleDir, "../assets/fonts", file),
    path.resolve(moduleDir, "../../assets/fonts", file),
    path.resolve(process.cwd(), "assets/fonts", file),
  ];
  for (const candidate of candidates) {
    try {
      readFileSync(candidate, { encoding: null });
      return candidate;
    } catch {
      // try next
    }
  }
  throw new Error(`OG card font not found: ${file}`);
}

let fontFiles: string[] | undefined;
function getFontFiles(): string[] {
  fontFiles ??= [findFont("DejaVuSans.ttf"), findFont("DejaVuSans-Bold.ttf")];
  return fontFiles;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export interface AreaCardInput {
  city: string;
  state: string;
  businessName: string;
  phone: string;
}

function buildSvg(input: AreaCardInput): string {
  const city = escapeXml(input.city);
  const state = escapeXml(input.state);
  const { brandSeparator: sep, brandSuffix } = OG_CARD_BRAND;
  const brand = escapeXml(
    [input.businessName, input.phone, brandSuffix].join(sep),
  );
  const B = OG_CARD_BRAND;
  return `<svg width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="wash" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#13233c"/>
      <stop offset="1" stop-color="${NAVY}"/>
    </linearGradient>
    <linearGradient id="edge" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#000000" stop-opacity="0"/>
      <stop offset="1" stop-color="#000000" stop-opacity="0.55"/>
    </linearGradient>
  </defs>
  <rect width="${WIDTH}" height="${HEIGHT}" fill="url(#wash)"/>
  <rect width="${WIDTH}" height="${HEIGHT}" fill="url(#edge)"/>
  <!-- subtle roofline accent -->
  <path d="M 780 630 L 1080 330 L 1380 630 Z" fill="#ffffff" fill-opacity="0.04"/>
  <path d="M 900 630 L 1200 330 L 1500 630 Z" fill="#ffffff" fill-opacity="0.04"/>
  <text x="${B.leftMargin}" y="300" font-family="${B.fontFamily}" font-weight="bold" font-size="${B.headlineSize}" fill="#ffffff">${city}, ${state}</text>
  <text x="${B.leftMargin}" y="388" font-family="${B.fontFamily}" font-weight="bold" font-size="${B.headlineSize}" fill="#ffffff">Roofing</text>
  <text x="${B.leftMargin}" y="472" font-family="${B.fontFamily}" font-size="${B.sublineSize}" fill="${B.sublineColor}">Roof repair, replacement &amp; storm</text>
  <text x="${B.leftMargin}" y="512" font-family="${B.fontFamily}" font-size="${B.sublineSize}" fill="${B.sublineColor}">restoration for ${city} homes.</text>
  <text x="${B.leftMargin}" y="580" font-family="${B.fontFamily}" font-weight="bold" font-size="${B.brandLineSize}" fill="${ACCENT}">${brand}</text>
  <rect x="0" y="${HEIGHT - B.footerBarHeight}" width="${WIDTH}" height="${B.footerBarHeight}" fill="${ACCENT}"/>
</svg>`;
}

// Cards are cheap to cache and the set of areas is small; keyed by the copy
// that goes into the image so a rename invalidates naturally.
const MAX_CACHE_ENTRIES = 200;
const cache = new Map<string, Buffer>();

export function renderAreaShareCard(input: AreaCardInput): Buffer {
  const key = [input.city, input.state, input.businessName, input.phone].join(
    "\u0000",
  );
  const cached = cache.get(key);
  if (cached) return cached;

  const resvg = new Resvg(buildSvg(input), {
    fitTo: { mode: "width", value: WIDTH },
    font: {
      fontFiles: getFontFiles(),
      loadSystemFonts: false,
      defaultFontFamily: "DejaVu Sans",
    },
  });
  const png = resvg.render().asPng();
  if (cache.size >= MAX_CACHE_ENTRIES) {
    const oldest = cache.keys().next().value;
    if (oldest !== undefined) cache.delete(oldest);
  }
  cache.set(key, Buffer.from(png));
  return cache.get(key) as Buffer;
}
